### ISSUE TITLE
Some(aMap["nonExistingKey"]).OrElse("FallBackValue")?

### ISSUE THREAD

**Issue by tigerinus** [samber/mo#15]
For `aMap map[string]string`, can I do `Some(aMap["nonExistingKey"]).OrElse("FallBackValue")`?

It seems to return empty string all the time.

Thanks.

**Comment by samber** [comment]
Hi @tigerinus 

I think you should use `mo.EmptyableToOption(aMap["nonExistingKey"]).OrElse(...)`.

`mo.Some` instantiate an Option with a value, even if this value is empty.

`mo.EmptyableToOption` check the zero value and calls `mo.None` or `mo.Some`
