### ISSUE TITLE
Option wrappers for slices and maps?

### ISSUE THREAD

**Issue by renom** [samber/mo#19]
Something like:
```
var s OptionSlice[[]int]
var m OptionMap[map[string]int]
fmt.Println(s.IsPresent(10), s.OrEmpty(10))
fmt.Println(m.IsPresent("key"), m.OrEmpty("key"))
```

**Comment by samber** [comment]
I think you should use github.com/samber/lo instead.

- lo.Contains
- lo.FindOrElse

**Comment by renom** [comment]
lo.Contains and lo.FindOrElse checks for a value, not for index/key

**Comment by renom** [comment]
returning the default value with OrEmpty would help avoiding out of bounds error for slices
