### ISSUE TITLE
Is there a good way to define a Future of nothing?

### ISSUE THREAD

**Issue by serbrech** [samber/mo#26]
Hi, this might be a noob question.

When doing an async computation, there are cases where we don't have a resolve value, but we might have an error.
Future requires to define a resolve type, since there is no non-generic definition.

Is that an unusual case for Future usage? Is there another construct that I should use?

**Comment by yougahu** [comment]
struct{} means nothing in golang. For example you can use map[T]struct{} as a set.

**Comment by samber** [comment]
I agree, this is the best way to do it.
