### ISSUE TITLE
swap documentation of functions IsAbsent and IsPresent

### ISSUE THREAD

**Issue by jcbritobr** [samber/mo#27]
struct Option functions IsAbsent and IsPresent has swaped documentation

IsAbsent says: **IsAbsent returns true when value is present.** - must returns false when value is present
IsPresent says: **IsPresent returns true when value is absent** - must return true when value is present

version - mo.1.8.0

**Comment by MatthiasKunnen** [comment]
Fixed in #22 but not yet released.
