### ISSUE TITLE
Irritating lack of type inference on Option for None and Result for Err

### ISSUE THREAD

**Issue by effinsky** [samber/mo#29]
I realize this is a limitation of the compiler's type inference mechanism but it looks bad to have to explicitly state a type parameter for the `None` and `Err` variants. Can anything be done to avoid this and clean up the use of `Option` and `Result`?

Here's what I mean for `Result`, for instance:
<img width="647" alt="Screenshot 2023-08-15 at 11 56 56" src="https://github.com/samber/mo/assets/54535543/e77715ae-3cfb-4254-9270-5fa79cd49415">

Here's what would be cooler:
<img width="688" alt="Screenshot 2023-08-15 at 11 56 42" src="https://github.com/samber/mo/assets/54535543/c169e762-0809-43e0-afaf-97093f91a4e7">

Ok, and here's what would be really nice, with options for wrapping this:
<img width="753" alt="Screenshot 2023-08-15 at 11 56 04" src="https://github.com/samber/mo/assets/54535543/d62be6ea-2279-474a-9818-3ace0f71efe7">

**Comment by samber** [comment]
I suppose we can add a `mo.Errf()` helper, but your first feedback is due to compiler limitation. Go is not able to infer `Err` generic type from the output generic type (here `Result[string]`).

**Comment by effinsky** [comment]
I know -- it hurts!

**Comment by samber** [comment]
Added to v1.10.0
