### ISSUE TITLE
Result.Map expects new result to be of the same type

### ISSUE THREAD

**Issue by Yakiyo** [samber/mo#31]
I only recently saw this library and it opened the doors to a lot of new stuff for me, i specially liked that it has types like Result and Option which are great for me, since i came from Rust. But what felt weird to me was the type of Result.Map
For a Result<T>, the `Map` function returns a new Result<T>, this allows me to modify the internal value but im restricted to it being the same type. 
On the otherhand in case of rust's Result, Result.Map converts a result of type `Result<T, E>` to `Result<U, E>`. I can convert the inner Ok value to a diff type, it can be either the same type or diff. while for mo's case, im bound to having the same type. The following exam fails in mo's case
```go
package main

import (
	"fmt"

	"github.com/samber/mo"
)

func main() {
	ok := mo.Ok([]string{"b"})
	r := ok.Map(func(value []string) (string, error) {
		return value[0], nil
	})
       fmt.Println(r.MustGet())
}
```
While i could just do `ok.MustGet()[0]` in this , this is usually not always the case when i'm returning a Result type from a custom function. It would be helpful if the Map function could convert type T to a new type U. Otherwise we explicitly need to unwrap the result, convert it and rewrap it in a result

**Comment by Yakiyo** [comment]
I just saw that apparantly struct methods can't have generic types when the struct itself has generics on it. So it feels like this isn't possible?

**Comment by Ocramius** [comment]
It looks like it would be possible to implement this the generic way via just free-floating `func` declarations, not attached to a `struct`: that would allow something like:

```go
func Map[T, U, V, Z](
  mo.SomeSymbol[T, U],
  func (T) (U, V)
) mo.SomeSymbol[U, V] { ... }
```

**Comment by Ocramius** [comment]
Wrote a dummy: feel free to shoot it down, but it's just an example.

```go
type either[T any, U error] struct {
	left  T
	right U
}

func left[T any, U error](left T) either[T, U] {
	return either[T, U]{
		left: left,
	}
}

func right[T any, U error](right U) either[T, U] {
	return either[T, U]{
		right: right,
	}
}

func flatMap[T any, U error, V any](in either[T, U], apply func(T) (V, U)) either[V, U] {
	if in.right != nil {
		return either[V, U]{
			right: in.right,
		}
	}

	left, err := apply(in.left)

	if err != nil {
		return either[V, U]{
			right: err,
		}
	}

	return either[V, U]{
		left: left,
	}
}
```
